//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheperd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FatoraDetail
    {
        public int fatoraDetailsId { get; set; }
        public Nullable<int> fatoraId { get; set; }
        public Nullable<int> productId { get; set; }
        public string productName { get; set; }
        public Nullable<decimal> productQuantity { get; set; }
        public decimal SellingPrice { get; set; }
        public decimal totalMoney { get; set; }
    
        public virtual Sale Sale { get; set; }
    }
}
