//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheperd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int productId { get; set; }
        public string productName { get; set; }
        public Nullable<decimal> buyingPrice { get; set; }
        public Nullable<decimal> sellingPrice { get; set; }
        public Nullable<decimal> productQuantity { get; set; }
        public string productDescription { get; set; }
        public string productPlace { get; set; }
    }
}
